baseURL = "https://darui.io/"
languageCode = "ja-jp"
title = "だるい"
theme = "minimo"

hasCJKLanguage = true

Paginate = 20


pygmentsCodefences = true
defaultContentLanguage = "ja"

[params]
author = "supermomonga"

[params.info]
description = "だるすぎる"
title404 = "う〜ん"


[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006年01月02日 15:04"
listDateFormat = "2006-01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = false


[params.opengraph.twitter]
page = "supermomonga"

[params.social]
github = "supermomonga"
twitter = "supermomonga"


[params.social.config]
platforms = ["github","twitter"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/page/:slug/"


[[menu.main]]
name = "Home"
weight = -10
identifier = "home"
url = "/"

[[menu.main]]
name = "Tags"
weight = 0
identifier = "tags"
url = "/tags"
