baseURL = "https://darui.io/"
languageCode = "ja-jp"
title = "だるい"
theme = "kiss"

hasCJKLanguage = true

defaultContentLanguage = "ja"

# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[params]
author = "supermomonga"

[params.social]
twitter = "supermomonga"
github = "supermomonga"

[permalinks]
page = "/page/:slug/"

[taxonomies]
tag ="tags"

