baseURL = "https://darui.io/"
languageCode = "ja-jp"
title = "だるい"
theme = "kiss"

hasCJKLanguage = true

Paginate = 20


pygmentsCodefences = true
defaultContentLanguage = "ja"

[params]
author = "supermomonga"

[params.highlight]
style = "github"

[[params.social]]
url = "https://github.com/supermomonga"
fa_icon = 'fa-github'

[[params.social]]
url = "https://twitter.com/supermomonga"
fa_icon = 'fa-twitter'

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[permalinks]
page = "/page/:slug/"


[[menu.main]]
name = "Home"
weight = -10
identifier = "home"
url = "/"

[[menu.main]]
name = "Tags"
weight = 0
identifier = "tags"
url = "/tags"
